{
  "formatVersion": "1.1",
  "component": {
    "group": "com.moneycollect.payment",
    "module": "android_mc",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "njm7nurzfjfcrp6pinywo3fmdy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle-android",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle-components",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.koin",
          "module": "koin-androidx-scope",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "org.koin",
          "module": "koin-androidx-viewmodel",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "org.koin",
          "module": "koin-androidx-fragment",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "compiler",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "jp.wasabeef",
          "module": "glide-transformations",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.tencent.sonic",
          "module": "sdk",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.1.0"
          }
        },
        {
          "group": "com.github.chuckerteam.chucker",
          "module": "library",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "android_mc-0.0.3.aar",
          "url": "android_mc-0.0.3.aar",
          "size": 1525583,
          "sha512": "eb8bbd5093ccc7d79258b5a1fc97d8c955ac3dc6db074f6b4b60bf31d2d2582233aa59659816210b420a71fb419f19837d0da601f321f2e0a8042f4c71e9cd37",
          "sha256": "bcbc426abb4a4e432550becb090e4f735e222d13e297459c630eab441ea7d063",
          "sha1": "f931dc3bbbd32917846a9d1b0b718732ea07880e",
          "md5": "0443a2d9a13e716b65be9ff36f0cf1db"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle-android",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle-components",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.koin",
          "module": "koin-androidx-scope",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "org.koin",
          "module": "koin-androidx-viewmodel",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "org.koin",
          "module": "koin-androidx-fragment",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "compiler",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "jp.wasabeef",
          "module": "glide-transformations",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.tencent.sonic",
          "module": "sdk",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.1.0"
          }
        },
        {
          "group": "com.github.chuckerteam.chucker",
          "module": "library",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "android_mc-0.0.3.aar",
          "url": "android_mc-0.0.3.aar",
          "size": 1525583,
          "sha512": "eb8bbd5093ccc7d79258b5a1fc97d8c955ac3dc6db074f6b4b60bf31d2d2582233aa59659816210b420a71fb419f19837d0da601f321f2e0a8042f4c71e9cd37",
          "sha256": "bcbc426abb4a4e432550becb090e4f735e222d13e297459c630eab441ea7d063",
          "sha1": "f931dc3bbbd32917846a9d1b0b718732ea07880e",
          "md5": "0443a2d9a13e716b65be9ff36f0cf1db"
        }
      ]
    }
  ]
}
