{
  "formatVersion": "1.1",
  "component": {
    "group": "com.moneycollect.payment",
    "module": "android_mc",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "yqvvsg4uszaolphbkuaosd4kgy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle-android",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle-components",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.koin",
          "module": "koin-androidx-scope",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "org.koin",
          "module": "koin-androidx-viewmodel",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "org.koin",
          "module": "koin-androidx-fragment",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "compiler",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "jp.wasabeef",
          "module": "glide-transformations",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.tencent.sonic",
          "module": "sdk",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.1.0"
          }
        },
        {
          "group": "com.github.chuckerteam.chucker",
          "module": "library",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "android_mc-0.0.7.aar",
          "url": "android_mc-0.0.7.aar",
          "size": 1523583,
          "sha512": "451c3c12e03ab43a811e3e57d79cefb7e5407b06964e7f5f7b3e1173d91a48b88ad1d5aec975c560837afc7d1dabb5648bf640ffae51b26d1eb235071318916d",
          "sha256": "e60a034931f259885008e6e42bf75aeac0f95c655add8f91b32decd524bfd52d",
          "sha1": "e69938ee4256f93291b65455bb5744c3f4ef4ba1",
          "md5": "f7a0cb841afebd3b71311b3c8c1c5ddb"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle-android",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.trello.rxlifecycle3",
          "module": "rxlifecycle-components",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.koin",
          "module": "koin-androidx-scope",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "org.koin",
          "module": "koin-androidx-viewmodel",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "org.koin",
          "module": "koin-androidx-fragment",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "compiler",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "jp.wasabeef",
          "module": "glide-transformations",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.tencent.sonic",
          "module": "sdk",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.1.0"
          }
        },
        {
          "group": "com.github.chuckerteam.chucker",
          "module": "library",
          "version": {
            "requires": "3.5.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "4.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "android_mc-0.0.7.aar",
          "url": "android_mc-0.0.7.aar",
          "size": 1523583,
          "sha512": "451c3c12e03ab43a811e3e57d79cefb7e5407b06964e7f5f7b3e1173d91a48b88ad1d5aec975c560837afc7d1dabb5648bf640ffae51b26d1eb235071318916d",
          "sha256": "e60a034931f259885008e6e42bf75aeac0f95c655add8f91b32decd524bfd52d",
          "sha1": "e69938ee4256f93291b65455bb5744c3f4ef4ba1",
          "md5": "f7a0cb841afebd3b71311b3c8c1c5ddb"
        }
      ]
    }
  ]
}
